<%@ page language="vb" masterpagefile="admin.master" autoeventwireup="true" inherits="admin_clients, App_Web_kw1ulmho" title="Clients Admin" stylesheettheme="Admin" enableEventValidation="false" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
    <div id="menutext" >
        <ul>
            <li><asp:HyperLink ID="linkUserGeneration" runat="server" NavigateUrl="admin_user_generation.aspx">GÉNÉRER des codes d'usagers</asp:HyperLink></li>
            <li><asp:HyperLink ID="linkAccountMerge" runat="server" NavigateUrl="admin_user_merge.aspx">COMBINER des codes d'usagers</asp:HyperLink></li>
            <li><asp:HyperLink ID="LinkAccountDuplicate" runat="server" NavigateUrl="admin_user_duplicate.aspx">DUPLIQUER des codes d'usagers</asp:HyperLink></li>
            <li><asp:HyperLink ID="LinkMovePhoto" runat="server" NavigateUrl="admin_user_move.aspx">DÉPLACER des photos</asp:HyperLink></li>
            <li><asp:HyperLink ID="LinkOrderForm"  runat="server" NavigateUrl="admin_user_paper_form.aspx">Bons de commande papier</asp:HyperLink></li>
        </ul>        
    </div>
    
    <h1>Recherche Usagers</h1>
    <hr />
    <table>
        <tr>            
            <td >
                UserName contenant: <asp:TextBox ID="txtUserName" runat="server"></asp:TextBox>
                <hr />
            </td>            
        </tr>
        <tr>
            <td >            
                <asp:CheckBox ID="chkAllUserTypes" runat="server" OnCheckedChanged="chkAllUserTypes_CheckedChanged" AutoPostBack="true" />
            </td>            
        </tr>
        <tr>
            <td >                
                <asp:CheckBoxList ID="chklstUserTypes" OnSelectedIndexChanged="chklstUserTypes_SelectedIndexChanged" runat="server"  AutoPostBack="true" RepeatDirection="Horizontal" RepeatColumns="10">
                </asp:CheckBoxList>                
            </td>            
        </tr>
        <tr>
            <td >
                <hr />
                <asp:Button ID="btnSearch" runat="server" Text="Rechercher" OnClick="btnSearch_Click" />
            </td>
        </tr>
    </table>
   
    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" datakeynames="username"
         ForeColor="#333333" GridLines="None" AllowPaging="True" PageSize="100">
        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="True" SortExpression="UserName" />
            <asp:templatefield headertext="Roles">
                <itemtemplate>
                    <asp:BulletedList ID="BulletedList1" runat="server" DataSource='<%# Eval("UserRoles") %>'>
                    </asp:BulletedList>                    
                </itemtemplate>                
            </asp:templatefield>
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:CheckBoxField DataField="IsOnline" HeaderText="IsOnline" ReadOnly="True" SortExpression="IsOnline" />
            <asp:CheckBoxField DataField="IsLockedOut" HeaderText="IsLockedOut"
                SortExpression="IsLockedOut" />
            <asp:BoundField DataField="CreationDate" HeaderText="CreationDate" ReadOnly="True"
                SortExpression="CreationDate" />
            <asp:BoundField DataField="LastLoginDate" HeaderText="LastLoginDate" SortExpression="LastLoginDate" />
        </Columns>
        <RowStyle BackColor="#E3EAEB" />
        <EditRowStyle BackColor="#7C6F57" />
        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" />
    </asp:GridView>
    
    <br />    
    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" autogenerateinsertbutton="True" autogeneratedeletebutton="true" autogenerateeditbutton="True" OnItemUpdating="DetailsView1_ItemUpdating" OnItemInserting="DetailsView1_ItemInserting"    onitemcommand="DetailsView1_ItemCommand"
        CellPadding="4" DataSourceID="ObjectDataSource2" ForeColor="#333333"
        GridLines="None" datakeynames="username">
        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <CommandRowStyle BackColor="#C5BBAF" Font-Bold="True" />
        <EditRowStyle BackColor="#7C6F57" />
        <RowStyle BackColor="#E3EAEB" />
        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
        <Fields>
            <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="True" SortExpression="UserName" />
            
            
            <asp:templatefield headertext="Roles">
                <itemtemplate>
                    <asp:BulletedList ID="RoleList" runat="server" DataSource='<%# Eval("UserRoles") %>'>
                    </asp:BulletedList>                    
                </itemtemplate>
                <EditItemTemplate>
                    <asp:BulletedList ID="RoleList" visible="false" runat="server" DataSource='<%# Eval("UserRoles") %>'>
                    </asp:BulletedList>
                    <asp:CheckBoxList ID="ChkRoles" runat="server" ondatabound="ChkRoles_DataBound" DataSource='<%# Roles.GetAllRoles() %>' RepeatDirection="Horizontal" RepeatColumns="8">
                    </asp:CheckBoxList>                    
                </EditItemTemplate>                
            </asp:templatefield>

            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />            
            <asp:BoundField DataField="Comment" HeaderText="Comment" SortExpression="Comment" />
            <asp:CheckBoxField DataField="IsOnline" insertvisible="False" HeaderText="IsOnline" ReadOnly="True" SortExpression="IsOnline" />
            <asp:CheckBoxField DataField="IsLockedOut" HeaderText="IsLockedOut" SortExpression="IsLockedOut" />
            <asp:CheckBoxField DataField="IsApproved" HeaderText="IsApproved" SortExpression="IsApproved" />
            <asp:BoundField DataField="LastPasswordChangedDate" insertvisible="False" HeaderText="LastPasswordChangedDate"
                ReadOnly="True" SortExpression="LastPasswordChangedDate" />
            <asp:BoundField DataField="CreationDate" insertvisible="False" HeaderText="CreationDate" ReadOnly="True"
                SortExpression="CreationDate" />
            <asp:BoundField DataField="LastLockoutDate" insertvisible="False" HeaderText="LastLockoutDate" ReadOnly="True"
                SortExpression="LastLockoutDate" />
            <asp:BoundField DataField="LastLoginDate" insertvisible="False" HeaderText="LastLoginDate" ReadOnly="True"
                SortExpression="LastLoginDate" />
            <asp:BoundField DataField="LastActivityDate" insertvisible="False" HeaderText="LastActivityDate" ReadOnly="True"
                SortExpression="LastActivityDate" />                        
            <asp:ButtonField Text="Show details" commandname="ShowDetails"/>
            <asp:ButtonField Text="Reset password" commandname="ResetPassword"/>
        </Fields>
        <FieldHeaderStyle BackColor="#D0D0D0" Font-Bold="True" />
        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" />
        
    </asp:DetailsView>    
    Password généré: 
    <asp:Label ID="labelPassword" runat="server" ></asp:Label>
    <br />   
    
    
    <asp:ObjectDataSource ID="ObjectDataSource2" runat="server" SelectMethod="GetUser" TypeName="System.Web.Security.Membership" >
        <SelectParameters>
            <asp:ControlParameter ControlID="GridView1" Name="username" PropertyName="SelectedDataKey.Value" Type="String" DefaultValue="-1" />
        </SelectParameters>        
    </asp:ObjectDataSource>
    
</asp:Content>