<%@ page language="vb" masterpagefile="admin.master" autoeventwireup="true" inherits="admin_categories, App_Web_kw1ulmho" title="Product Categories" stylesheettheme="Admin" enableEventValidation="false" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
	<h1>Product Categories</h1>
	<asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
		AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CategoryID"
		DataSourceID="SqlDataSource1">
		<Columns>
			<asp:BoundField DataField="CategoryID" HeaderText="CategoryID" InsertVisible="False" ReadOnly="True" SortExpression="CategoryID" />
			<asp:BoundField DataField="CategoryName" HeaderText="CategoryName" SortExpression="CategoryName" />
			<asp:CheckBoxField DataField="IsActive" HeaderText="IsActive" SortExpression="IsActive" />
			<asp:BoundField DataField="HelperImage" HeaderText="HelperImage" SortExpression="HelperImage" />
			<asp:BoundField DataField="DisplayImage" HeaderText="DisplayImage" SortExpression="DisplayImage" />
		</Columns>
	</asp:GridView>
	<br />
	<h1>Add Category</h1><br />
	<asp:FormView ID="FormView1" runat="server" DataKeyNames="CategoryID" DataSourceID="SqlDataSource1"
		DefaultMode="Insert">
		 <InsertItemTemplate>
			 CategoryName:
			 <asp:TextBox ID="CategoryNameTextBox" runat="server" Text='<%#Bind("CategoryName")%>'>
			 </asp:TextBox><br />
			 Is Active:
             <asp:CheckBox ID="chkIsActive" Checked='<%#Bind("IsActive")%>' runat="server" /><br />
             HelperImage:
			 <asp:TextBox ID="txtHelperImage" runat="server" Text='<%#Bind("HelperImage")%>'>
			 </asp:TextBox><br />
			 DisplayImage:
			 <asp:TextBox ID="txtDisplayImage" runat="server" Text='<%#Bind("DisplayImage")%>'>
			 </asp:TextBox><br />
			 <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert"
				 Text="Insert">
			 </asp:LinkButton>
		</InsertItemTemplate>
		
		<ItemTemplate>
			CategoryID:
			<asp:Label ID="CategoryIDLabel" runat="server" Text='<%#Eval("CategoryID")%>'>
			</asp:Label><br />
			CategoryName:
			<asp:Label ID="CategoryNameLabel" runat="server" Text='<%#Bind("CategoryName")%>'>
			</asp:Label><br />
		</ItemTemplate>
	</asp:FormView>
	<br />
	<br />
	<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
		SelectCommand="SELECT * FROM [CMRC_Categories] ORDER BY [CategoryName]" 
		DeleteCommand="DELETE FROM [CMRC_Categories] WHERE [CategoryID] = @CategoryID" 
		InsertCommand="INSERT INTO [CMRC_Categories] ([CategoryName],[IsActive],[HelperImage],[DisplayImage]) VALUES (@CategoryName,@IsActive,@HelperImage,@DisplayImage)" 
		UpdateCommand="UPDATE [CMRC_Categories] SET [CategoryName] = @CategoryName, [IsActive] = @IsActive, [HelperImage] = @HelperImage, [DisplayImage] = @DisplayImage WHERE [CategoryID] = @CategoryID">
		<DeleteParameters>
			<asp:Parameter Name="CategoryID" Type="Int32" />
		</DeleteParameters>
		<UpdateParameters>
			<asp:Parameter Name="CategoryName" Type="String" />
			<asp:Parameter Name="CategoryID" Type="Int32" />
			<asp:Parameter Name="IsActive" Type="Int32" />
			<asp:Parameter Name="HelperImage" Type="String" />
			<asp:Parameter Name="DisplayImage" Type="String" />
		</UpdateParameters>
		<InsertParameters>
			<asp:Parameter Name="CategoryName" Type="String" />
			<asp:Parameter Name="IsActive" Type="Int32" />
			<asp:Parameter Name="HelperImage" Type="String" />
			<asp:Parameter Name="DisplayImage" Type="String" />
		</InsertParameters>
	</asp:SqlDataSource>

</asp:Content>

