<%@ page autoeventwireup="true" debug="true" inherits="Admin_admin_horaire, App_Web_4_qobto4" language="VB" masterpagefile="~/Admin/admin.master" smartnavigation="true" stylesheettheme="Admin" title="Horaire" enableEventValidation="false" %>

<asp:Content ID="Content1" runat="Server" ContentPlaceHolderID="AdminPlaceHolder">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    
    <h1>Horaire des rendez-vous</h1>
    Sélectionner l'événement :
    <asp:DropDownList ID="EventDDL" runat="server" AutoPostBack="true" DataTextField="Name"
        DataValueField="Code">
    </asp:DropDownList>
    <br /><br />
    
    <table border="1">
        <tr>
            <td>
                <h1>Ajouter une journée</h1>
            </td>
        </tr>
        <tr>
            <td>
                <table id="tblAddNewSchedule" runat="server" visible="false">
                    <tr>
                        <th>Date</th>
                        <th>Heure de début</th>
                        <th>Heure de fin</th>
                        <th>Durée d'un rendez-vous</th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr align="center">
                        <td>
                            <asp:TextBox ID="txtDate" runat="server"></asp:TextBox>
                            <asp:ImageButton ID="btnScheduledDate" runat="server" ImageUrl="~/Images/Calendar_scheduleHS.png" /><br />
                            <ajaxToolkit:CalendarExtender ID="CalendarExtender1" runat="server" Format="yyyy-MM-dd"
                                PopupButtonID="btnScheduledDate" TargetControlID="txtDate">
                            </ajaxToolkit:CalendarExtender>
                        </td>
                        <td>
                            <asp:TextBox ID="txtheureDebut" runat="server" MaxLength="5">hh:mm</asp:TextBox>
                        </td>
                        <td>
                            <asp:TextBox ID="txtheureFin" runat="server" MaxLength="5">hh:mm</asp:TextBox>
                        </td>
                        <td>
                            <asp:TextBox ID="txtdureePeriode" runat="server" MaxLength="2" Text="En minute"></asp:TextBox>
                        </td>
                        <td>
                            <asp:Button ID="btnInsertNewSchedule" runat="server" OnClick="btnInsertNewSchedule_Click" Text="Ajouter" />
                        </td>
                        <td>
                            <asp:Button ID="btnCancelNewSchedule" runat="server" OnClick="btnCancelNewSchedule_Click" Text="Cancel" />
                        </td>
                    </tr>
                </table>
            </td>       
        </tr>
        <tr>
            <td>
                <asp:LinkButton ID="btnAddNewSchedule" runat="server" CausesValidation="false" OnClick="btnAddNewSchedule_Click" Text="Add"></asp:LinkButton>
            </td>
        </tr>
    </table>   
    
    <br />
    <h1>Journées cédulées :</h1>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
         OnRowCommand="GridView1_RowCommand" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" 
         DataKeyNames="ScheduleID" DataSourceID="SqlDataSource1">
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" /> 
        <RowStyle HorizontalAlign="Center" />
        <Columns>
            <asp:BoundField  DataField="ScheduleId" HeaderText="ScheduleId" Visible="false" />
            <asp:BoundField DataField="Date" DataFormatString="{0:d}" HeaderText="Date" HtmlEncode="False" SortExpression="Date" />
            <asp:BoundField DataField="heureDebut" DataFormatString="{0:HH:mm}" HeaderText="Heure de début" HtmlEncode="False" />
            <asp:BoundField DataField="heureFin" DataFormatString="{0:HH:mm}" HeaderText="Heure de fin" HtmlEncode="False" />
            <asp:BoundField DataField="dureePeriode" HeaderText="Durée d'un rendez-vous" />
            <asp:ButtonField CommandName="ShowDetails" Text="Show details" />
        </Columns>
        <EditRowStyle BackColor="#FFFAE0" />
    </asp:GridView>
    &nbsp;
    
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
        DeleteCommand="DELETE FROM [CMRC_RendezVous] WHERE [ScheduleID] = @ScheduleID
                       DELETE FROM [CMRC_ScheduleRendezVous] WHERE [ScheduleID] = @ScheduleID"
        SelectCommand="SELECT * FROM [CMRC_ScheduleRendezVous] WHERE [EventUserName] = @EventUserName ORDER BY [Date] ASC"
        UpdateCommand="CMRC_ScheduleRendezVous_Update" UpdateCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="ScheduleId" Type="Object" />
        </DeleteParameters>
        <SelectParameters>
            <asp:ControlParameter Name="EventUserName" ControlID="EventDDL" PropertyName="SelectedValue" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="ScheduleId" Type="Object" />
            <asp:Parameter Name="Date" Type="Datetime" />
            <asp:Parameter Name="heureDebut" Type="Datetime" />
            <asp:Parameter Name="heureFin" Type="Datetime" />
            <asp:Parameter Name="dureePeriode" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    
</asp:Content>
